version: '3.8'

services:
  core:
    build: .
    command: python core.py
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://microservice:microservice@db_core/core
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
    depends_on:
      db_core:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/backendservice
    networks:
      - shared_network

  core_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python3 -u consumer.py'
    environment:
      - DATABASE_URL=mysql://microservice:microservice@db_core/core
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
    depends_on:
      - db_core
      - rabbitmq
    volumes:
      - .:/backendservice
    networks:
      - shared_network

  db_core:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: core
      MYSQL_USER: microservice
      MYSQL_PASSWORD: microservice
      MYSQL_ROOT_PASSWORD: microservice
    volumes:
      - db_data_core:/var/lib/mysql
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_network

volumes:
  db_data_core:

networks:
  shared_network:
    external: true
